---
name: 01 Basic Docker Build
# simplest workflow possible

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-image:
    name: Build Image
    runs-on: ubuntu-latest
    steps:
            
      - name: Send 111
        run: echo "Hello ${{ env.DOCKERHUB_USERNAME }}"
      
      - name: Send greeting
        run: echo "Hello ${{ inputs.name }}"
