---
name: 01 Basic Docker Build
# simplest workflow possible

on:
  push:
    branches:
      - main

jobs:
  build-image:
    name: Build Image
    runs-on: ubuntu-latest
    steps:
            
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}